version: '3'
services:
  # Existing services
  pg:
    image: postgis/postgis:16-3.4
    restart: always
    container_name: pg
    ports:
      - 6500:5432
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: data-volume
        target: /var/lib/postgresql/data

  motis-import:
    image: ghcr.io/motis-project/motis:2.0
    volumes:
      - ./GTFS.zip:/input/GTFS.zip
      - ./osm.pbf:/input/osm.pbf
      - ./config.yml:/config.yml
      - motis-data:/data:rw
    command: /bin/sh -c "./motis import"

  motis-server:
    image: ghcr.io/motis-project/motis:2.0
    depends_on:
      - motis-import
    volumes:
      - motis-data:/data:rw
    ports:
      - 6499:8080
    command: /bin/sh -c "cd / && /motis server"

  prima:
    image: prima
    restart: always
    ports:
      - 7777:3000
    environment:
      - DATABASE_URL=postgresql://postgres:pw@pg/prima
      - ORIGIN=http://localhost:7777
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317  # Tempo for traces
      - OTEL_RESOURCE_ATTRIBUTES=service.name=prima
    build:
      context: .
    networks:
      - monitoring

  # Grafana stack services
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - monitoring

  loki:
    image: grafana/loki:3.4.0
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - 3200:3200
    volumes:
      - ./tempo-config.yaml:/etc/tempo/config.yaml  # Mount your config file
      - tempo-data:/var/tempo   # Mount the local storage volume
    networks:
      - monitoring


volumes:
  data-volume:
  motis-data:
  tempo-data:

networks:
  monitoring:
