//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::blocked_times::Entity as BlockedTimes;
pub use super::company::Entity as Company;
pub use super::event::Entity as Event;
pub use super::user::Entity as User;
pub use super::vehicle::Entity as Vehicle;
pub use super::zone::Entity as Zone;
